export const el = {
  nav: { tournaments: 'Αρχική', schedule: 'Πρόγραμμα', teams: 'Ομάδες', archive: 'Αρχείο', news: 'News', rentals: 'Ενοικιάσεις', contact: 'Επικοινωνία', register: 'Δήλωση συμμετοχής' },
  hero: { kicker: 'Επόμενη στάση', title1: 'Το γήπεδο', title2: 'δεν κοιμάται ποτέ', cta1: 'Δήλωσε ομάδα', cta2: 'Δες το πρόγραμμα', matchdayBlurb: 'Ό,τι παίζεται τώρα, ό,τι έρχεται και ό,τι μόλις τελείωσε — σε τρεις κάρτες που ενημερώνονται ζωντανά από τη γραμματεία.', mapKicker: 'πόλεις · #NEXTSTOPYOURCITY · κλικ σε πόλη', soon: 'Το πρόγραμμα ανακοινώνεται σύντομα.', contactBtn: 'Επικοινωνία', stop: { next: 'Πρόγραμμα', reg: 'Δηλώσεις', soon: 'Σύντομα' } },
  sections: { matchday1: 'Το γήπεδο', matchday2: 'περιμένει', now1: 'Τώρα', now2: 'στο γήπεδο', results: 'Τελευταία αποτελέσματα', schedule1: 'Επερχόμενες', schedule2: 'διοργανώσεις', news1: 'Latest', news2: 'news', shop1: 'Ενοικιάσεις', shop2: '& διοργάνωση', viewNews: 'Όλα τα νέα', viewShop: 'Όλες οι υπηρεσίες', standings1: 'Βαθμολογίες', standings2: 'ομίλων', ko: 'Νοκ-άουτ', tour1: 'Η περιοδεία', archive1: 'Αρχείο', archive2: 'διοργανώσεων', sponsors: 'Χορηγοί & συνεργάτες', newsletter1: 'Μπες', newsletter2: 'στη λίστα' },
  status: { live: 'Live', startsIn: 'Ξεκινά σε', done: 'Ολοκληρώθηκε', final: 'Τελικό', scheduled: 'Προγραμματισμένος', optional: 'Προαιρετικό', noLive: 'Κανένας αγώνας σε εξέλιξη', nextMatch: 'Επόμενος αγώνας', seeLive: 'Δες live →', schedule: 'Πρόγραμμα →', results: 'Αποτελέσματα →', winners: 'Νικητές ανά κατηγορία', teams: 'ομάδες', cats: 'κατηγορίες', courts: 'γήπεδα' },
  table: { pos: '#', team: 'Ομάδα', gp: 'ΑΓ', wl: 'Ν–Η', pts: 'Π+/Π–', points: 'Β' },
  misc: { courtShort: 'Γ', court: 'Γήπεδο', all: 'Όλες', viewAll: 'Όλες οι διοργανώσεις', schedulePdf: 'PDF προγράμματος', follow: 'Ακολούθησέ μας', email: 'Το email σου', subscribe: 'Εγγραφή', newsletterBlurb: 'Νέες διοργανώσεις, άνοιγμα δηλώσεων και προγράμματα, πριν από όλους. Χωρίς spam.' },
  footer: { tagline: 'Τουρνουά 3on3 σε όλη την Ελλάδα από το 2018. Παιδιά, έφηβοι, ενήλικες, βετεράνοι.', terms: 'Όροι', privacy: 'Απόρρητο' },
  bracket: { r16: 'Φάση των 16', qf: 'Προημιτελικοί', sf: 'Ημιτελικοί', final: 'Τελικός' },
  tour: { tabs: { schedule: 'Πρόγραμμα', groups: 'Όμιλοι', ko: 'Νοκ-άουτ', teams: 'Ομάδες', info: 'Πληροφορίες' }, groupPhase: 'Φάση ομίλων', koPhase: 'Νοκ-άουτ', groupsBy: 'ανά κατηγορία', noMatches: 'Δεν υπάρχουν αγώνες με αυτά τα φίλτρα.', koSoon: 'Τα νοκ-άουτ ανακοινώνονται μετά τους ομίλους.', noTeams: 'Καμία δήλωση ακόμη.', info: 'Πληροφορίες', venue: 'Γήπεδο', address: 'Διεύθυνση', hours: 'Ώρες', game: 'Αγώνας', checkin: 'Check-in', directions: 'Οδηγίες στον χάρτη →', sub: (days: string, courts: number, cats: number) => `${days}, ${courts} γήπεδα. Όμιλοι και νοκ-άουτ σε ${cats} κατηγορίες.`, teamsN: 'ομάδες', groupsN: 'όμιλοι' },
  team: { next1: 'Επόμενος', next2: 'αγώνας', allMatches: 'Όλοι οι αγώνες', noNext: 'Δεν υπάρχει προγραμματισμένος αγώνας.', calendar: 'Προσθήκη στο ημερολόγιο', bracket: 'Δες το πρόγραμμα', theTeam: 'Η ομάδα', category: 'Κατηγορία', city: 'Πόλη', group: 'Όμιλος', captain: 'Αρχηγός', matches: 'Αγώνες', roster: 'Ρόστερ', player: 'Παίκτης', noRoster: 'Το ρόστερ συμπληρώνεται από τον αρχηγό μέσω του συνδέσμου πρόσκλησης.', legend: 'Μπλε = προκρίνονται · Πορτοκαλί = η ομάδα σου', history1: 'Ιστορικό', history2: 'ομάδας', wl: 'Νίκες–Ήττες', diff: 'Διαφορά', players: 'Παίκτες', inProgress: 'Σε εξέλιξη', qualified: 'προκρίθηκε στα νοκ-άουτ', notify: 'Ειδοποίηση 15΄ πριν σε όλους τους παίκτες της ομάδας.' },
  player: { kicker: 'Παίκτης', myMatches1: 'Οι αγώνες μου', myMatches2: 'σήμερα', myTeam: 'Η ομάδα μου', teamPage: 'Σελίδα ομάδας →', schedule: 'Πρόγραμμα →', stats: 'Στατιστικά παίκτη', statsSoon: 'Πόντοι, ρεκόρ, MVP ανά αγώνα — Φάση 2 (απαιτεί καταγραφή από τη γραμματεία).', history1: 'Ιστορικό', history2: 'συμμετοχών', participations: 'Συμμετοχές', wins: 'Νίκες', matches: 'Αγώνες', invite: 'Πρόσκληση συμπαίκτη', qr: 'QR check-in' },
  news: { read: 'Διάβασε →', more: 'Περισσότερα', share: 'Κοινοποίηση:', copy: 'Αντιγραφή συνδέσμου', copied: 'Αντιγράφηκε ✓', full: 'Διάβασε ολόκληρο το άρθρο στο gnc3on3.gr ↗' },
  contact: { title1: 'Επικοινωνία', email: 'Email', hq: 'Έδρα', hours: 'Ώρες', hoursV: 'Δευ–Παρ 10:00–18:00 · τις μέρες τουρνουά στο γήπεδο', social: 'Social', note: 'Για δηλώσεις ομάδων χρησιμοποίησε τη φόρμα δήλωσης — όχι το email — ώστε να μπεις αυτόματα στη λίστα.', name: 'Όνομα', subject: 'Θέμα', message: 'Μήνυμα', send: 'Αποστολή', sent: 'Στάλθηκε. Απαντάμε συνήθως μέσα σε μία εργάσιμη.' },
  rentals: { quote: 'Ζήτησε προσφορά', ask: 'Ζήτησε', ask2: 'προσφορά', how1: 'Πώς', how2: 'δουλεύει' },
  live: { title: 'Live', noLive: 'Κανένας αγώνας σε εξέλιξη', next: 'Επόμενος', court: 'Γήπεδο' },
  loading: 'Φόρτωση…',
}
export type Dict = typeof el
