export const el = {
  nav: { tournaments: 'Αρχική', schedule: 'Πρόγραμμα', teams: 'Ομάδες', archive: 'Αρχείο', news: 'News', rentals: 'Ενοικιάσεις', contact: 'Επικοινωνία', register: 'Δήλωση συμμετοχής' },
  hero: { kicker: 'Επόμενη στάση', title1: 'Το γήπεδο', title2: 'δεν κοιμάται ποτέ', cta1: 'Δήλωσε ομάδα', cta2: 'Δες το πρόγραμμα', matchdayBlurb: 'Ό,τι παίζεται τώρα, ό,τι έρχεται και ό,τι μόλις τελείωσε — σε τρεις κάρτες που ενημερώνονται ζωντανά από τη γραμματεία.', mapKicker: 'πόλεις · #NEXTSTOPYOURCITY · κλικ σε πόλη', soon: 'Το πρόγραμμα ανακοινώνεται σύντομα.', contactBtn: 'Επικοινωνία', stop: { next: 'Πρόγραμμα', reg: 'Δηλώσεις', soon: 'Σύντομα' } },
  sections: { matchday1: 'Το γήπεδο', matchday2: 'περιμένει', now1: 'Τώρα', now2: 'στο γήπεδο', results: 'Τελευταία αποτελέσματα', schedule1: 'Επερχόμενες', schedule2: 'διοργανώσεις', news1: 'Latest', news2: 'news', shop1: 'Ενοικιάσεις', shop2: '& διοργάνωση', viewNews: 'Όλα τα νέα', viewShop: 'Όλες οι υπηρεσίες', standings1: 'Βαθμολογίες', standings2: 'ομίλων', ko: 'Νοκ-άουτ', tour1: 'Η περιοδεία', archive1: 'Αρχείο', archive2: 'διοργανώσεων', sponsors: 'Χορηγοί & συνεργάτες', newsletter1: 'Μπες', newsletter2: 'στη λίστα' },
  status: { live: 'Live', startsIn: 'Ξεκινά σε', done: 'Ολοκληρώθηκε', final: 'Τελικό', scheduled: 'Προγραμματισμένος', optional: 'Προαιρετικό', noLive: 'Κανένας αγώνας σε εξέλιξη', nextMatch: 'Επόμενος αγώνας', seeLive: 'Δες live →', schedule: 'Πρόγραμμα →', results: 'Αποτελέσματα →', winners: 'Νικητές ανά κατηγορία', teams: 'ομάδες', cats: 'κατηγορίες', courts: 'γήπεδα' },
  table: { pos: '#', team: 'Ομάδα', gp: 'ΑΓ', wl: 'Ν–Η', pts: 'Π+/Π–', points: 'Β' },
  misc: { court: 'Γήπεδο', all: 'Όλες', viewAll: 'Όλες οι διοργανώσεις', schedulePdf: 'PDF προγράμματος', follow: 'Ακολούθησέ μας', email: 'Το email σου', subscribe: 'Εγγραφή', newsletterBlurb: 'Νέες διοργανώσεις, άνοιγμα δηλώσεων και προγράμματα, πριν από όλους. Χωρίς spam.' },
  footer: { tagline: 'Τουρνουά 3on3 σε όλη την Ελλάδα από το 2018. Παιδιά, έφηβοι, ενήλικες, βετεράνοι.', terms: 'Όροι', privacy: 'Απόρρητο' },
}
export type Dict = typeof el
