import type { Dict } from './el'
export const en: Dict = {
  nav: { tournaments: 'Home', schedule: 'Schedule', teams: 'Teams', archive: 'Archive', news: 'News', rentals: 'Rentals', contact: 'Contact', register: 'Register a team' },
  hero: { kicker: 'Next stop', title1: 'The court', title2: 'never sleeps', cta1: 'Register a team', cta2: 'See the schedule', matchdayBlurb: 'What is playing now, what is next and what just finished — three cards updated live by the secretariat.', mapKicker: 'cities · #NEXTSTOPYOURCITY · click a city', soon: 'The schedule will be announced soon.', contactBtn: 'Contact us', stop: { next: 'Schedule', reg: 'Register', soon: 'Soon' } },
  sections: { matchday1: 'The court', matchday2: 'awaits', now1: 'On the', now2: 'court now', results: 'Latest results', schedule1: 'Upcoming', schedule2: 'tournaments', news1: 'Latest', news2: 'news', shop1: 'Rentals', shop2: '& events', viewNews: 'All news', viewShop: 'All services', standings1: 'Group', standings2: 'standings', ko: 'Knockout', tour1: 'The tour', archive1: 'Tournament', archive2: 'archive', sponsors: 'Sponsors & partners', newsletter1: 'Join', newsletter2: 'the list' },
  status: { live: 'Live', startsIn: 'Starts in', done: 'Completed', final: 'Final', scheduled: 'Scheduled', optional: 'Optional', noLive: 'No game in progress', nextMatch: 'Next game', seeLive: 'Watch live →', schedule: 'Schedule →', results: 'Results →', winners: 'Winners by category', teams: 'teams', cats: 'categories', courts: 'courts' },
  table: { pos: '#', team: 'Team', gp: 'GP', wl: 'W–L', pts: 'PF/PA', points: 'Pts' },
  misc: { court: 'Court', all: 'All', viewAll: 'All tournaments', schedulePdf: 'Schedule PDF', follow: 'Follow us', email: 'Your email', subscribe: 'Subscribe', newsletterBlurb: 'New tournaments, registration openings and schedules, before everyone else. No spam.' },
  footer: { tagline: '3on3 tournaments across Greece since 2018. Kids, teens, adults, veterans.', terms: 'Terms', privacy: 'Privacy' },
}
