import type { Dict } from './el'
export const en: Dict = {
  nav: { tournaments: 'Home', schedule: 'Schedule', teams: 'Teams', archive: 'Archive', news: 'News', rentals: 'Rentals', contact: 'Contact', register: 'Register a team' },
  hero: { kicker: 'Next stop', title1: 'The court', title2: 'never sleeps', cta1: 'Register a team', cta2: 'See the schedule', matchdayBlurb: 'What is playing now, what is next and what just finished — three cards updated live by the secretariat.', mapKicker: 'cities · #NEXTSTOPYOURCITY · click a city', soon: 'The schedule will be announced soon.', contactBtn: 'Contact us', stop: { next: 'Schedule', reg: 'Register', soon: 'Soon' } },
  sections: { matchday1: 'The court', matchday2: 'awaits', now1: 'On the', now2: 'court now', results: 'Latest results', schedule1: 'Upcoming', schedule2: 'tournaments', news1: 'Latest', news2: 'news', shop1: 'Rentals', shop2: '& events', viewNews: 'All news', viewShop: 'All services', standings1: 'Group', standings2: 'standings', ko: 'Knockout', tour1: 'The tour', archive1: 'Tournament', archive2: 'archive', sponsors: 'Sponsors & partners', newsletter1: 'Join', newsletter2: 'the list' },
  status: { live: 'Live', startsIn: 'Starts in', done: 'Completed', final: 'Final', scheduled: 'Scheduled', optional: 'Optional', noLive: 'No game in progress', nextMatch: 'Next game', seeLive: 'Watch live →', schedule: 'Schedule →', results: 'Results →', winners: 'Winners by category', teams: 'teams', cats: 'categories', courts: 'courts' },
  table: { pos: '#', team: 'Team', gp: 'GP', wl: 'W–L', pts: 'PF/PA', points: 'Pts' },
  misc: { courtShort: 'C', court: 'Court', all: 'All', viewAll: 'All tournaments', schedulePdf: 'Schedule PDF', follow: 'Follow us', email: 'Your email', subscribe: 'Subscribe', newsletterBlurb: 'New tournaments, registration openings and schedules, before everyone else. No spam.' },
  footer: { tagline: '3on3 tournaments across Greece since 2018. Kids, teens, adults, veterans.', terms: 'Terms', privacy: 'Privacy' },
  bracket: { r16: 'Round of 16', qf: 'Quarter-finals', sf: 'Semi-finals', final: 'Final' },
  tour: { tabs: { schedule: 'Schedule', groups: 'Groups', ko: 'Knockout', teams: 'Teams', info: 'Info' }, groupPhase: 'Group phase', koPhase: 'Knockout', groupsBy: 'by category', noMatches: 'No matches match these filters.', koSoon: 'The knockout is announced after the groups.', noTeams: 'No registrations yet.', info: 'Info', venue: 'Venue', address: 'Address', hours: 'Hours', game: 'Game', checkin: 'Check-in', directions: 'Directions on the map →', sub: (days: string, courts: number, cats: number) => `${days}, ${courts} courts. Groups and knockout in ${cats} categories.`, teamsN: 'teams', groupsN: 'groups' },
  team: { next1: 'Next', next2: 'game', allMatches: 'All games', noNext: 'No game scheduled.', calendar: 'Add to calendar', bracket: 'See the schedule', theTeam: 'The team', category: 'Category', city: 'City', group: 'Group', captain: 'Captain', matches: 'Games', roster: 'Roster', player: 'Player', noRoster: 'The roster is completed by the captain through the invite link.', legend: 'Blue = qualify · Orange = your team', history1: 'Team', history2: 'history', wl: 'Wins–Losses', diff: 'Diff', players: 'Players', inProgress: 'In progress', qualified: 'qualified for the knockout', notify: 'All players get a notification 15΄ before.' },
  player: { kicker: 'Player', myMatches1: 'My games', myMatches2: 'today', myTeam: 'My team', teamPage: 'Team page →', schedule: 'Schedule →', stats: 'Player stats', statsSoon: 'Points, records, MVP per game — Phase 2 (requires scorekeeping at the desk).', history1: 'Participation', history2: 'history', participations: 'Tournaments', wins: 'Wins', matches: 'Games', invite: 'Invite a teammate', qr: 'QR check-in' },
  news: { read: 'Read →', more: 'More', share: 'Share:', copy: 'Copy link', copied: 'Copied ✓', full: 'Read the full article on gnc3on3.gr ↗' },
  contact: { title1: 'Contact', email: 'Email', hq: 'Based in', hours: 'Hours', hoursV: 'Mon–Fri 10:00–18:00 · on tournament days at the venue', social: 'Social', note: 'To register a team use the registration form — not email — so you enter the list automatically.', name: 'Name', subject: 'Subject', message: 'Message', send: 'Send', sent: 'Sent. We usually reply within one working day.' },
  rentals: { quote: 'Request a quote', ask: 'Request', ask2: 'a quote', how1: 'How it', how2: 'works' },
  live: { title: 'Live', noLive: 'No game in progress', next: 'Next', court: 'Court' },
  loading: 'Loading…',
}
